### ISSUE TITLE
Discord bot permissions

### ISSUE THREAD

**Issue by GameBurrow** [shoter/OpenttdDiscord#10]
What permissions does the bot need? Eveything seemed to work up until I tried to use change_password. DM never came through.

**Comment by GameBurrow** [comment]
Fixed itself for some strange reason. Closing

**Comment by shoter** [comment]
Thanks for the opening issue. i am going to repoen it and assign myself to it. I am going to add section to readme about it.

**Comment by shoter** [comment]
Done
